
SET IDENTITY_INSERT [Provinces] OFF
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (1, N'Hà Nội', N'Thành Phố', 4, NULL,  24, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (2, N'Hà Giang', N'Tỉnh', 219, NULL,  22, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (4, N'Cao Bằng', N'Tỉnh', 710, NULL,  14, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (6, N'Bắc Kạn', N'Tỉnh', 281, NULL,  4, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (8, N'Tuyên Quang', N'Tỉnh', 27, NULL,  60, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (10, N'Lào Cai', N'Tỉnh', 63, NULL,  38, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (11, N'Điện Biên', N'Tỉnh', 61, NULL,  18, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (12, N'Lai Châu', N'Tỉnh', 231, NULL,  35, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (14, N'Sơn La', N'Tỉnh', 22, NULL,  52, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (15, N'Yên Bái', N'Tỉnh', 29, NULL,  63, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (17, N'Hòa Bình', N'Tỉnh', 321, NULL,  30, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (19, N'Thái Nguyên', N'Tỉnh', 280, NULL,  55, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (20, N'Lạng Sơn', N'Tỉnh', 25, NULL,  37, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (22, N'Quảng Ninh', N'Tỉnh', 33, NULL,  49, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (24, N'Bắc Giang', N'Tỉnh', 781, NULL,  3, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (25, N'Phú Thọ', N'Tỉnh', 210, NULL,  44, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (26, N'Vĩnh Phúc', N'Tỉnh', 211, NULL,  62, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (27, N'Bắc Ninh', N'Tỉnh', 241, NULL,  6, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (30, N'Hải Dương', N'Tỉnh', 320, NULL,  26, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (31, N'Hải Phòng', N'Thành Phố', 31, NULL,  27, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (33, N'Hưng Yên', N'Tỉnh', 8, NULL,  31, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (34, N'Thái Bình', N'Tỉnh', 36, NULL,  54, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (35, N'Hà Nam', N'Tỉnh', 351, NULL,  23, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (36, N'Nam Định', N'Tỉnh', 350, NULL,  40, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (37, N'Ninh Bình', N'Tỉnh', 30, NULL,  42, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (38, N'Thanh Hóa', N'Tỉnh', 37, NULL,  56, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (40, N'Nghệ An', N'Tỉnh', 38, NULL,  41, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (42, N'Hà Tĩnh', N'Tỉnh', 39, NULL,  25, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (44, N'Quảng Bình', N'Tỉnh', 52, NULL,  46, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (45, N'Quảng Trị', N'Tỉnh', 53, NULL,  50, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (46, N'Thừa Thiên Huế', N'Tỉnh', 54, NULL,  57, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (48, N'Đà Nẵng', N'Thành Phố', 511, NULL,  15, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (49, N'Quảng Nam', N'Tỉnh', 510, NULL,  47, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (51, N'Quảng Ngãi', N'Tỉnh', 55, NULL,  48, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (52, N'Bình Định', N'Tỉnh', 650, NULL,  8, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (54, N'Phú Yên', N'Tỉnh', 57, NULL,  45, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (56, N'Khánh Hòa', N'Tỉnh', 58, NULL,  32, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (58, N'Ninh Thuận', N'Tỉnh', 68, NULL,  43, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (60, N'Bình Thuận', N'Tỉnh', 62, NULL,  11, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (62, N'Kon Tum', N'Tỉnh', 60, NULL,  34, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (64, N'Gia Lai', N'Tỉnh', 59, NULL,  21, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (66, N'Đắk Lắk', N'Tỉnh', 500, NULL,  16, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (67, N'Đắk Nông', N'Tỉnh', 501, NULL,  17, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (68, N'Lâm Đồng', N'Tỉnh', 20, NULL,  36, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (70, N'Bình Phước', N'Tỉnh', 651, NULL,  10, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (72, N'Tây Ninh', N'Tỉnh', 66, NULL,  53, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (74, N'Bình Dương', N'Tỉnh', 56, NULL,  9, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (75, N'Đồng Nai', N'Tỉnh', 67, NULL,  19, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (77, N'Bà Rịa - Vũng Tàu', N'Tỉnh', 64, NULL,  2, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (79, N'Hồ Chí Minh', N'Thành Phố', 711, NULL,  29, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (80, N'Long An', N'Tỉnh', 72, NULL,  39, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (82, N'Tiền Giang', N'Tỉnh', 73, NULL,  58, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (83, N'Bến Tre', N'Tỉnh', 75, NULL,  7, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (84, N'Trà Vinh', N'Tỉnh', 74, NULL,  59, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (86, N'Vĩnh Long', N'Tỉnh', 70, NULL,  61, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (87, N'Đồng Tháp', N'Tỉnh', 230, NULL,  20, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (89, N'An Giang', N'Tỉnh', 76, NULL,  1, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (91, N'Kiên Giang', N'Tỉnh', 77, NULL,  33, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (92, N'Cần Thơ', N'Thành Phố', 26, NULL,  13, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (93, N'Hậu Giang', N'Tỉnh', 218, NULL,  28, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (94, N'Sóc Trăng', N'Tỉnh', 79, NULL,  51, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (95, N'Bạc Liêu', N'Tỉnh', 240, NULL,  5, 1 )
INSERT [dbo].[Provinces] ([Id], [Name], [Type], [TelephoneCode], [ZipCode],  [SortOrder], [Status]) VALUES (96, N'Cà Mau', N'Tỉnh', 780, NULL,  12, 1 )